hideOverlays = "RELOADING"
rgbProgress = false
blockOverlay = false
miniRender = true
enableScissor = false
type = "PROGRESS"
reloadText = "Loading..."
resetResources = false
reInitScreen = true
removeOverlayAtEnd = true
earlyPackStatusSend = false
doubleLoad = "FORCE_LOAD"
animationSpeed = 1000.0
