debug = false
disable_crowdin = false
check_for_updates = true

[[key_bindings]]
name = "key.plasmovoice.proximity.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 3
type = "MOUSE"


[addons.pv-addon-soundphysics]
"gui.plasmovoice.soundphysics.mic_reverb_volume" = 1.0
"gui.plasmovoice.soundphysics.enabled" = true
"gui.plasmovoice.soundphysics.mic_reverb" = true

[voice]
disabled = false
microphone_disabled = false
activation_threshold = -32.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 1.0
noise_suppression = true
volume = 1.65
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = false
stereo_capture = true

[voice.volumes.proximity]
volume = 1.0
[voice.volumes.groups]
volume = 1.0
[voice.volumes.source_42a7f6ec-78bb-4722-86d8-0bdfd419e8dd]
volume = 1.0
[voice.volumes.source_371264a4-b808-4d99-ab03-9ec0b33f04bf]
volume = 1.0
[voice.volumes.source_0b656a9a-2ab8-4df0-8fe5-1969506432c0]
volume = 1.0
[voice.volumes.source_f636887e-fe29-483a-b144-1222ed4eb656]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "ON"
groups = "WHEN_TALKING"
